model_list:
  - model_name: bedrock-claude-3-5-sonnet-v1
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0
      temperature: 0.7
      max_tokens: 4096
      top_p: 0.95
      top_k: 200

  - model_name: bedrock-claude-3-haiku
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0
      temperature: 0.7
      max_tokens: 4096
      top_p: 0.95
      top_k: 200
